// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/note.proto

/*
Package istio_vet_v1 is a generated protocol buffer package.

It is generated from these files:
	api/v1/note.proto

It has these top-level messages:
	Info
	Note
*/
package istio_vet_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NoteLevel indicates the severity level of the note
type NoteLevel int32

const (
	NoteLevel_UNUSED  NoteLevel = 0
	NoteLevel_INFO    NoteLevel = 1
	NoteLevel_WARNING NoteLevel = 2
	NoteLevel_ERROR   NoteLevel = 3
)

var NoteLevel_name = map[int32]string{
	0: "UNUSED",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
}
var NoteLevel_value = map[string]int32{
	"UNUSED":  0,
	"INFO":    1,
	"WARNING": 2,
	"ERROR":   3,
}

func (x NoteLevel) String() string {
	return proto.EnumName(NoteLevel_name, int32(x))
}
func (NoteLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Vetters use Info to provide their information
type Info struct {
	// Name of the vetter
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Semver string of the vetter
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Info) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Info) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Vetters generate Notes after inspecting the mesh configuration
type Note struct {
	// MD5 checksum of the generated note
	//
	// Used as UUID for notes
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Type of the note
	//
	// Example "istio-component-mismatch", "missing-service-port-prefix"
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// Short description of the note
	//
	// Summary may contain python template strings "${var}" which will be
	// substituted from values in Attr map described below. Summary
	// should only refer to template variables present in Attr map.
	Summary string `protobuf:"bytes,3,opt,name=summary" json:"summary,omitempty"`
	// Long description of the note
	//
	// Similar to Summary, Msg can contain python template strings "${var}" which
	// will be substituted from values in Attr map described below. Msg
	// should only refer to template variables present in Attr map.
	Msg string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
	// Severity of the note
	Level NoteLevel `protobuf:"varint,5,opt,name=level,enum=istio.vet.v1.NoteLevel" json:"level,omitempty"`
	// Map of template variables which can be used by Summary and Msg
	Attr map[string]string `protobuf:"bytes,6,rep,name=Attr" json:"Attr,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Note) Reset()                    { *m = Note{} }
func (m *Note) String() string            { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()               {}
func (*Note) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Note) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Note) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Note) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Note) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Note) GetLevel() NoteLevel {
	if m != nil {
		return m.Level
	}
	return NoteLevel_UNUSED
}

func (m *Note) GetAttr() map[string]string {
	if m != nil {
		return m.Attr
	}
	return nil
}

func init() {
	proto.RegisterType((*Info)(nil), "istio.vet.v1.Info")
	proto.RegisterType((*Note)(nil), "istio.vet.v1.Note")
	proto.RegisterEnum("istio.vet.v1.NoteLevel", NoteLevel_name, NoteLevel_value)
}

func init() { proto.RegisterFile("api/v1/note.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x35, 0x6d, 0xba, 0xd9, 0x3b, 0x19, 0xf5, 0x22, 0x18, 0xc4, 0x87, 0xb1, 0xa7, 0x21, 0x98,
	0x7d, 0xf8, 0xe0, 0xc7, 0xdb, 0xc0, 0x29, 0x03, 0xe9, 0x20, 0x32, 0x7c, 0x9e, 0x2c, 0x4a, 0xb0,
	0x6d, 0x4a, 0x9b, 0x05, 0xfa, 0xaf, 0xfd, 0x09, 0x92, 0xb6, 0x1b, 0xc2, 0xde, 0xce, 0x39, 0xf7,
	0xe4, 0x9e, 0x93, 0x0b, 0xe7, 0x9b, 0x5c, 0x8d, 0xed, 0x74, 0x9c, 0x69, 0x23, 0x79, 0x5e, 0x68,
	0xa3, 0xf1, 0x4c, 0x95, 0x46, 0x69, 0x6e, 0xa5, 0xe1, 0x76, 0x3a, 0x9c, 0x00, 0x5d, 0x66, 0x5f,
	0x1a, 0xfb, 0xe0, 0xa9, 0x2d, 0x23, 0x03, 0x32, 0x0a, 0x85, 0xa7, 0xb6, 0xc8, 0xa0, 0x6b, 0x65,
	0x51, 0x2a, 0x9d, 0x31, 0xaf, 0x16, 0xf7, 0x74, 0xf8, 0x4b, 0x80, 0xc6, 0xda, 0xc8, 0xa3, 0x27,
	0x08, 0xd4, 0x54, 0xb9, 0x6c, 0xfd, 0x35, 0x76, 0x6b, 0xca, 0x5d, 0x9a, 0x6e, 0x8a, 0x8a, 0xf9,
	0xcd, 0x9a, 0x96, 0x62, 0x04, 0x7e, 0x5a, 0x7e, 0x33, 0x5a, 0xab, 0x0e, 0xe2, 0x2d, 0x04, 0x89,
	0xb4, 0x32, 0x61, 0xc1, 0x80, 0x8c, 0xfa, 0xb3, 0x4b, 0xfe, 0xbf, 0x28, 0x77, 0x91, 0x6f, 0x6e,
	0x2c, 0x1a, 0x17, 0x4e, 0x80, 0xce, 0x8d, 0x29, 0x58, 0x67, 0xe0, 0x8f, 0x7a, 0xb3, 0xeb, 0x63,
	0x37, 0x77, 0xe3, 0x45, 0x66, 0x8a, 0x4a, 0xd4, 0xce, 0xab, 0x7b, 0x08, 0x0f, 0x92, 0xcb, 0xff,
	0x91, 0x55, 0x5b, 0xdf, 0x41, 0xbc, 0x80, 0xc0, 0x6e, 0x92, 0xdd, 0xfe, 0x03, 0x0d, 0x79, 0xf2,
	0x1e, 0xc8, 0xcd, 0x23, 0x84, 0x87, 0x78, 0x04, 0xe8, 0xac, 0xe3, 0xf5, 0xfb, 0xe2, 0x39, 0x3a,
	0xc1, 0x53, 0xa0, 0xcb, 0xf8, 0x65, 0x15, 0x11, 0xec, 0x41, 0xf7, 0x63, 0x2e, 0xe2, 0x65, 0xfc,
	0x1a, 0x79, 0x18, 0x42, 0xb0, 0x10, 0x62, 0x25, 0x22, 0xff, 0xb3, 0x53, 0x1f, 0xfd, 0xee, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0xca, 0x98, 0xb2, 0x98, 0x89, 0x01, 0x00, 0x00,
}
